/* 
 * Workiva Developer API
 *
 * APIs provided for 3rd party integrations. Build: c0ca649
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type ErrorResponse struct {

	// A list of errors detailing the resource, field, and error code to aid  clients in diagnosing problems. 
	Errors []ModelError `json:"errors,omitempty"`

	// Human readable description of the response
	Message string `json:"message,omitempty"`

	RequestId string `json:"request_id,omitempty"`
}
