/* 
 * Workiva Developer API
 *
 * APIs provided for 3rd party integrations. Build: c0ca649
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type RangeDataResponse struct {

	Data RangeData `json:"data,omitempty"`

	// Human readable descriptions of the response condition
	Message string `json:"message,omitempty"`

	// A fully qualified URL, including required query parameters, for the  next page of results. If there is no next page to query for, this will  be empty. 
	NextUrl string `json:"next_url,omitempty"`

	// The one based page index that the result corresponds to. Only included during paging. 
	Page int32 `json:"page,omitempty"`

	// The entire region that the collection of pages represents. Only included during data paging. 
	PagedRegion string `json:"paged_region,omitempty"`

	// The maximum number of items in a page. A page is not guaranteed to have exactly this many items. Only included during paging. 
	PerPage int32 `json:"per_page,omitempty"`

	// A unique identifier for the request
	RequestId string `json:"request_id,omitempty"`

	// The revision number of this spreadsheet
	Revision int32 `json:"revision,omitempty"`
}
