/* 
 * Workiva Developer API
 *
 * APIs provided for 3rd party integrations. Build: c0ca649
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

import (
	"time"
)

type Spreadsheet struct {

	// Date-time (UTC) corresponding to the creation of the Spreadsheet
	Created time.Time `json:"created,omitempty"`

	// Unique identifier for the Spreadsheet
	Id string `json:"id,omitempty"`

	// Date-time (UTC) corresponding to the last modification of the Spreadsheet
	LastModified time.Time `json:"last_modified,omitempty"`

	// Display name for the Spreadsheet
	Name string `json:"name,omitempty"`
}
